// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDULMOcKqPCdjy49eFVcEAWB2w3whvh_RU',
    appId: '1:986066052439:web:a9ec9057f6b3e706aa4a12',
    messagingSenderId: '986066052439',
    projectId: 'fredh-carpintaria',
    authDomain: 'fredh-carpintaria.firebaseapp.com',
    storageBucket: 'fredh-carpintaria.appspot.com',
    measurementId: 'G-9HBEYL4QR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Lu65mZG4dO-PKTLOahkT9aEmrhTfnAY',
    appId: '1:986066052439:android:833d1b15a69b95e4aa4a12',
    messagingSenderId: '986066052439',
    projectId: 'fredh-carpintaria',
    storageBucket: 'fredh-carpintaria.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVY6q5hcONaGFqXEi_UeqAn0Y69hZZCRk',
    appId: '1:986066052439:ios:22640efc7e385a4aaa4a12',
    messagingSenderId: '986066052439',
    projectId: 'fredh-carpintaria',
    storageBucket: 'fredh-carpintaria.appspot.com',
    iosBundleId: 'com.example.fredhLda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVY6q5hcONaGFqXEi_UeqAn0Y69hZZCRk',
    appId: '1:986066052439:ios:22640efc7e385a4aaa4a12',
    messagingSenderId: '986066052439',
    projectId: 'fredh-carpintaria',
    storageBucket: 'fredh-carpintaria.appspot.com',
    iosBundleId: 'com.example.fredhLda',
  );
}
